language: shell

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - zsh
    - os: osx

install:
  - nvm install --lts

script:
  - tests/test.zsh
