name: Bug Report
description: Create a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. In order to help us better understand the problem, please fill out the issue template below.
  - type: textarea
    attributes:
      label: OS version
      placeholder: Ubuntu 24.04
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: zsh version
      description: '`zsh --version` output'
      placeholder: zsh 5.9 (x86_64-ubuntu-linux-gnu)
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: awk version
      description: '`awk --version` or `awk -W version` output'
      placeholder: 'GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)'
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: jq version
      description: '`jq --version` output'
      placeholder: jq-1.7
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: fzf version
      description: '`fzf --version` output'
      placeholder: 0.44.1 (debian)
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command version(s)
      description: 'Command version(s) for completing command (e.g., `git --version` for git completion)'
      placeholder: git version 2.43.0
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Locale
      description: '`locale` output'
      placeholder: |
        LANG=en_US.UTF-8
        LC_CTYPE="en_US.UTF-8"
        LC_NUMERIC="en_US.UTF-8"
        LC_TIME="en_US.UTF-8"
        LC_COLLATE="en_US.UTF-8"
        LC_MONETARY="en_US.UTF-8"
        LC_MESSAGES=en_US.UTF-8
        LC_PAPER="en_US.UTF-8"
        LC_NAME="en_US.UTF-8"
        LC_ADDRESS="en_US.UTF-8"
        LC_TELEPHONE="en_US.UTF-8"
        LC_MEASUREMENT="en_US.UTF-8"
        LC_IDENTIFICATION="en_US.UTF-8"
        LC_ALL=
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Aliases (if applicable)
      description: '`alias` output'
      placeholder: |
        g='git'
        gc='git commit'
        k='kubectl'
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Options
      description: '`setopt` output'
      placeholder: |
        extendedglob
        magicequalsubst
        nonomatch
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Installed zsh plugins (if applicable)
      description: '`antigen list`, `zplug list`, and their equivalents’ output'
      placeholder: zsh-users/zsh-completions @ master
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the command as it is, regardless of aliases.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true
